# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_coaching4.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    #Jet:从.ui原始PyUic转换成的文件，运行时，UI不会出现，需要修改,参见modify_to_Run
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1284, 982)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1261, 911))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 3, 1, 2)
        self.radioButton_s1iscoach = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_s1iscoach.setChecked(False)
        self.radioButton_s1iscoach.setObjectName("radioButton_s1iscoach")
        self.gridLayout.addWidget(self.radioButton_s1iscoach, 2, 1, 1, 1)
        self.btn_save_raw_to_txt = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_save_raw_to_txt.setObjectName("btn_save_raw_to_txt")
        self.gridLayout.addWidget(self.btn_save_raw_to_txt, 9, 2, 1, 1)
        self.radioButton_s2isclient = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_s2isclient.setCheckable(True)
        self.radioButton_s2isclient.setObjectName("radioButton_s2isclient")
        self.gridLayout.addWidget(self.radioButton_s2isclient, 2, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.tableWidget_raw = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget_raw.setObjectName("tableWidget_raw")
        self.tableWidget_raw.setColumnCount(0)
        self.tableWidget_raw.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_raw, 7, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 3, 1, 1)
        self.btn_stop_audio = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_stop_audio.setObjectName("btn_stop_audio")
        self.gridLayout.addWidget(self.btn_stop_audio, 9, 1, 1, 1)
        self.horizontalSlider_audio = QtWidgets.QSlider(self.gridLayoutWidget)
        self.horizontalSlider_audio.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_audio.setObjectName("horizontalSlider_audio")
        self.gridLayout.addWidget(self.horizontalSlider_audio, 8, 0, 1, 3)
        self.lineEdit_audio_file = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_audio_file.setObjectName("lineEdit_audio_file")
        self.gridLayout.addWidget(self.lineEdit_audio_file, 0, 1, 1, 4)
        self.btn_play_audio = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_play_audio.setObjectName("btn_play_audio")
        self.gridLayout.addWidget(self.btn_play_audio, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.radioButton_s2iscoach = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_s2iscoach.setCheckable(True)
        self.radioButton_s2iscoach.setChecked(True)
        self.radioButton_s2iscoach.setObjectName("radioButton_s2iscoach")
        self.gridLayout.addWidget(self.radioButton_s2iscoach, 2, 5, 1, 1)
        self.btn_locate_audio_file = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_locate_audio_file.setObjectName("btn_locate_audio_file")
        self.gridLayout.addWidget(self.btn_locate_audio_file, 0, 0, 1, 1)
        self.radioButton_s1isclient = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_s1isclient.setObjectName("radioButton_s1isclient")
        self.gridLayout.addWidget(self.radioButton_s1isclient, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 5, 1, 1)
        self.tableWidget_icf = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget_icf.setObjectName("tableWidget_icf")
        self.tableWidget_icf.setColumnCount(0)
        self.tableWidget_icf.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_icf, 7, 3, 1, 3)
        self.btn_locate_output_path = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_locate_output_path.setObjectName("btn_locate_output_path")
        self.gridLayout.addWidget(self.btn_locate_output_path, 10, 0, 1, 1)
        self.radioButton_export_stat = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_export_stat.setObjectName("radioButton_export_stat")
        self.gridLayout.addWidget(self.radioButton_export_stat, 10, 3, 1, 1)
        self.btn_save_icf_to_txt = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_save_icf_to_txt.setObjectName("btn_save_icf_to_txt")
        self.gridLayout.addWidget(self.btn_save_icf_to_txt, 10, 4, 1, 1)
        self.btn_save_icf_to_word = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_save_icf_to_word.setObjectName("btn_save_icf_to_word")
        self.gridLayout.addWidget(self.btn_save_icf_to_word, 10, 5, 1, 1)
        self.tableWidget_stat = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget_stat.setObjectName("tableWidget_stat")
        self.tableWidget_stat.setColumnCount(0)
        self.tableWidget_stat.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_stat, 8, 3, 2, 3)
        self.lineEdit_output_path = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_output_path.setObjectName("lineEdit_output_path")
        self.gridLayout.addWidget(self.lineEdit_output_path, 10, 1, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 1)
        self.gridLayout.setColumnStretch(5, 1)
        self.gridLayout.setRowStretch(7, 12)
        self.gridLayout.setRowStretch(8, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1284, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.radioButton_s1iscoach.toggled['bool'].connect(self.radioButton_s1isclient.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "（注：讯飞转写可能存在少量错误，请根据实际录音编辑，满意之后再保存)"))
        self.radioButton_s1iscoach.setText(_translate("MainWindow", "教练"))
        self.btn_save_raw_to_txt.setText(_translate("MainWindow", "保存原始文稿到txt文档"))
        self.radioButton_s2isclient.setText(_translate("MainWindow", "客户"))
        self.label.setText(_translate("MainWindow", "请按实际情况指定：Speaker1："))
        self.label_2.setText(_translate("MainWindow", "Speaker2："))
        self.btn_stop_audio.setText(_translate("MainWindow", "停止"))
        self.btn_play_audio.setText(_translate("MainWindow", "播放"))
        self.label_5.setText(_translate("MainWindow", "（注：讯飞转写可能存在少量错误，请根据实际录音编辑)"))
        self.label_4.setText(_translate("MainWindow", "ICF教练文稿格式："))
        self.label_3.setText(_translate("MainWindow", "讯飞转写原始文稿："))
        self.radioButton_s2iscoach.setText(_translate("MainWindow", "教练"))
        self.btn_locate_audio_file.setText(_translate("MainWindow", "请选择录音文件(mp3/wav)"))
        self.radioButton_s1isclient.setText(_translate("MainWindow", "客户"))
        self.label_7.setText(_translate("MainWindow", "Logo Empower All"))
        self.btn_locate_output_path.setText(_translate("MainWindow", "请选择默认保存目录"))
        self.radioButton_export_stat.setText(_translate("MainWindow", "输出包含统计信息"))
        self.btn_save_icf_to_txt.setText(_translate("MainWindow", "保存教练文稿到txt文档"))
        self.btn_save_icf_to_word.setText(_translate("MainWindow", "保存教练文稿到Word文档"))
        self.menu.setTitle(_translate("MainWindow", "教练录音转写助手"))
